### PR TITLE
Backport fix for Mojarra issue #4547

### PR DESCRIPTION
**Pull request by jasonex7**
- Upstream PR: https://github.com/eclipse-ee4j/mojarra/pull/4668
- https://github.com/eclipse-ee4j/mojarra/issues/4547

### CODE REVIEW

**Comment by jasonex7** [comment]
Hi @fjuma could you please review this backport? The upstream PR in eclipse-ee4j was already merged eclipse-ee4j/mojarra#4668. Thanks in advance.

**Comment by fjuma** [comment]
@jasonex7 Thanks for creating this PR! I'm going to cherry-pick the commit directly from the eclipse-ee4j/2.3 branch and then will release Mojarra 2.3.14.SP01.

**Comment by fjuma** [comment]
This has now been backported to the 2.3.14.SP branch and 2.3.14.SP01 has been released:
https://github.com/jboss/mojarra/commit/6a41ea363f2488d829ffddd21fb2eee955968a39

I've also submitted a PR to update to the 2.3.14.SP01 version in WildFly:
https://github.com/wildfly/wildfly/pull/13578

**Comment by jasonex7** [comment]
@fjuma Thanks for your help!

**Pull request closed without merging**
