### PR TITLE
JBEAP-19981 JSF deployment failure due to UnsupportedOperationExcepti…

### PR DESCRIPTION
**Pull request by RanabirChakraborty**
Issue: https://issues.redhat.com/browse/JBEAP-19981

Upstream PR: https://github.com/eclipse-ee4j/mojarra/pull/4748
2.3.14.SP PR: https://github.com/jboss/mojarra/pull/85

Test: https://github.com/jbossas/jboss-eap7/pull/3780

### CODE REVIEW

**Comment by fjuma** [comment]
After discussing this one with @rmartinc, it sounds like this is safe for us to go ahead and merge.

@RanabirChakraborty We'll also need a PR against the 2.3.14.SP branch since that is the version WildFly master is now on.

@spyrkob Are you able to merge this and tag 2.3.9.SP13 for EAP 7.3.5? If not, let me know, and I'll handle it. Thanks!

**Comment by spyrkob** [comment]
Sure, I'll merge it later this week.

**Comment by fjuma** [comment]
Thanks very much @spyrkob!

**Comment by RanabirChakraborty** [comment]
@fjuma I have raised a PR against 2.3.14.SP branch

**Pull request merged**
