### PR TITLE
[JBEAP-19407] Expire next flash cache during cookie decode

### PR DESCRIPTION
**Pull request by spyrkob**
JIRA: https://issues.redhat.com/browse/JBEAP-19407

### CODE REVIEW

**Comment by fjuma** [comment]
@spyrkob Just wanted to check on the status of this one. Is there a PR upstream for this or is this a backport of an existing fix upstream?

**Comment by spyrkob** [comment]
@fjuma yes it's a backport of one of the commits in https://github.com/eclipse-ee4j/mojarra/pull/4633/commits that was missing in 2.3.9.SP branch

**Comment by fjuma** [comment]
@spyrkob Great, feel free to merge this one then. Looks like we can also merge https://github.com/jboss/mojarra/pull/72 since JBEAP-19593 is acked. I can try to tag later today.

**Comment by spyrkob** [comment]
Thanks @fjuma. I also merged https://github.com/jboss/jboss-jakarta-faces-api/pull/9 since it's part of JBEAP-19593, so we'll need the API release as well.

**Comment by fjuma** [comment]
Thanks very much @spyrkob! Will create both tags this afternoon.

**Pull request merged**
