### PR TITLE
Alternative 2.3.9.sp

### PR DESCRIPTION
**Pull request by soul2zimate**
issue: https://issues.redhat.com/browse/WFLY-13497
Alternative fix for community report issue jboss/mojarra#71

impact: If context parameter javax.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL set to True, then an empty value from UIInput component is not set to null any more.

reproducer: https://github.com/soul2zimate/quickstart/tree/jsf-wrong-behaviour/helloworld-jsf

workaround: Do not enable the context parameter javax.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL for the moment.

### CODE REVIEW

**Comment by soul2zimate** [comment]
upstream PR https://github.com/eclipse-ee4j/mojarra/pull/4706 was approved.

**Comment by fjuma** [comment]
@soul2zimate Are there corresponding JBEAP issues created for these various PRs? Or is this fix needed for community only?

**Comment by soul2zimate** [comment]
None, so far it's only needed by the community user for WFLY.

**Comment by fjuma** [comment]
@soul2zimate Just took a closer look at this. Since these changes involve reverting the fix for JBEAP-17931, I think it would be good to get JBEAP issues created for this as well.

**Comment by erickdeoliveiraleal** [comment]
If possible merge it to Wildfly 20 release, please

**Pull request merged**
