### PR TITLE
[WFLY-11275] Backport PAYARA-2791

### PR DESCRIPTION
**Pull request by codylerum**
Backports PAYARA-2791 into jboss fork of mojarra to fix https://issues.jboss.org/browse/WFLY-11275

### CODE REVIEW

**Comment by codylerum** [comment]
@fjuma or @treblereel can you take a look at this and possibly get a patched version in WF 16?

**Comment by fjuma** [comment]
@codylerum Has a PR also been submitted upstream against https://github.com/eclipse-ee4j/mojarra?

**Comment by codylerum** [comment]
@fjuma Not yet due to the Jakarta migration.

See https://github.com/eclipse-ee4j/mojarra/issues/4509#issuecomment-453188481

**Comment by fjuma** [comment]
@codylerum Thanks! Please also create a WFLY JIRA issue for this.

**Comment by codylerum** [comment]
@fjuma in addition to https://issues.jboss.org/browse/WFLY-11275 or is that sufficient?

**Comment by fjuma** [comment]
@codylerum Apologies, was reading quickly and didn't notice the WFLY issue was already mentioned. Thanks again!

**Comment by codylerum** [comment]
@fjuma No apologies necessary. Thanks for looking.

**Comment by codylerum** [comment]
@fjuma do you think there is a chance this makes WF 16? If there is anything I can do to help it along please let me know.

**Comment by fjuma** [comment]
@codylerum Yes, this should make WF 16 (just been busy with some other things). The code freeze for WF 16 is in mid-February so I have this on my to-do list for the first week in February. I've just added a [2.3.8.SP](https://github.com/jboss/mojarra/tree/2.3.8.SP) branch to this repo, would you be able to close this PR and re-submit against that branch since we will likely want to upgrade to Mojarra 2.3.8 in WF 16.

**Comment by codylerum** [comment]
@fjuma  Will do!

**Comment by codylerum** [comment]
@fjuma I was able to change the base on this full request (didn't know you could do that) and rebase it off  2.3.8.SP so it should be good to merge in.

**Comment by fjuma** [comment]
Thanks @codylerum.

**Comment by fjuma** [comment]
@codylerum Just wanted to let you know that I'm working on the Mojarra component upgrade for WildFly 16 that includes this fix. Will let you know as soon as the component upgrade PR has been submitted against WildFly.

**Comment by codylerum** [comment]
@fjuma Thanks for keeping me in the loop and please let me know if there is anything I can do to help. If it makes it into a 16 alpha or beta I'll be sure to confirm the fix.

**Comment by fjuma** [comment]
Since 2.3.9 is now available, I've incorporated the changes for this PR into a 2.3.9.SP branch instead:

https://github.com/jboss/mojarra/commit/b025d57e7eff7ab976244c0d79c1a03cec8a4a13

The component upgrade PR is here:

https://github.com/wildfly/wildfly/pull/12062

**Comment by fjuma** [comment]
@codylerum Just FYI, WildFly 16.0.0.Beta1 has been tagged:

https://github.com/wildfly/wildfly/tree/16.0.0.Beta1

**Comment by codylerum** [comment]
@fjuma Thanks! I wasn't able to get my primary application to deploy for testing due to https://issues.jboss.org/projects/WFLY/issues/WFLY-11716

I'm going to try and spin up my simple reproducer for this issue today.

**Comment by codylerum** [comment]
@fjuma  Confirmed fixed in WF 16 Beta1

**Comment by fjuma** [comment]
Great, thanks @codylerum!

**Pull request closed without merging**
